
const { createApp } = Vue;

const textos = {
    pt: {
        titulo: "Classificação",
    },
    en: {
        titulo: "Standings",
    }
}

createApp({
    computed: {
        titulo () {
            return textos[this.seletorDeIdioma.selecionado].titulo;
        },
        selecionado () {
            return this.seletorDeIdioma.idiomas
                    .find((idioma) => idioma.codigo === this.seletorDeIdioma.selecionado)
                    ?.nome ?? 'Idioma';
        }
    },
    data() {
        return {
            seletorDeIdioma: {
                visivel: false,
                selecionado: "pt",
                idiomas: [
                    { codigo: "pt", nome: "Português" },
                    { codigo: "en", nome: "English" },
                ]
            },
            grupos: [
                {
                    letra: "B",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Brasil",
                            sigla: "BRA",
                            alt: "bandeira do brasil",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 3, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Senegal",
                            sigla: "SEN",
                            alt: "bandeira do senegal",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Tchéquia",
                            sigla: "CZE",
                            alt: "bandeira da tchequia",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Uzbequistão",
                            sigla: "UZB",
                            alt: "bandeira do uzbequistao",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -3, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "C",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Argentina",
                            sigla: "ARG",
                            alt: "bandeira da argentina",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 2, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Dinamarca",
                            sigla: "DEN",
                            alt: "bandeira da dinamarca",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Tunísia",
                            sigla: "TUN",
                            alt: "bandeira da tunisia",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Emirados Árabes Unidos",
                            sigla: "UAE",
                            alt: "bandeira dos emirados arabes unidos",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -2, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "D",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Espanha",
                            sigla: "ESP",
                            alt: "bandeira da espanha",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 3, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Equador",
                            sigla: "ECU",
                            alt: "bandeira do equador",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Qtar",
                            sigla: "QAT",
                            alt: "bandeira do qtar",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Suécia",
                            sigla: "SWE",
                            alt: "bandeira da suecia",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -3, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ]
                },
                {
                    letra: "E",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Itália",
                            sigla: "ITA",
                            alt: "bandeira da italia",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "RI do Irã",
                            sigla: "IRN",
                            alt: "bandeira do ira",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Camarões",
                            sigla: "CMR",
                            alt: "bandeira de camaroes",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Honduras",
                            sigla: "HON",
                            alt: "bandeira de honduras",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "F",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Suíça",
                            sigla: "SUI",
                            alt: "bandeira da suiça",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 2, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "China",
                            sigla: "CHN",
                            alt: "bandeira da china",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Panamá",
                            sigla: "PAN",
                            alt: "bandeira do panama",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Costa do Marfim",
                            sigla: "CIV",
                            alt: "bandeira da costa do Marfim",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -2, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "G",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Países Baixos",
                            sigla: "NED",
                            alt: "bandeira dos paises baixos",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 2, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Colômbia",
                            sigla: "COL",
                            alt: "bandeira da colombia",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Egito",
                            sigla: "EGY",
                            alt: "bandeira do egito",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Nova Zelândia",
                            sigla: "NZL",
                            alt: "bandeira da nova zelandia",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -2, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "H",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Peru",
                            sigla: "PER",
                            alt: "bandeira do peru",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Austria",
                            sigla: "AUT",
                            alt: "bandeira da austria",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "País de Gales",
                            sigla: "WAL",
                            alt: "bandeira do pais de galesl",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Jordânia",
                            sigla: "JOR",
                            alt: "bandeira da jordania",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "I",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Austrália",
                            sigla: "AUS",
                            alt: "bandeira da australia",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Portugal",
                            sigla: "POR",
                            alt: "bandeira de portugal",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Bélgica",
                            sigla: "BEL",
                            alt: "bandeira da belgica",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Paraguai",
                            sigla: "PAR",
                            alt: "bandeira do paraguai",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "J",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Croácia",
                            sigla: "CRO",
                            alt: "bandeira da croacia",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Canadá",
                            sigla: "CAN",
                            alt: "bandeira do canada",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Gana",
                            sigla: "GHA",
                            alt: "bandeira de gana",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Bahrein",
                            sigla: "BHR",
                            alt: "bandeira de bahrein",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "K",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Arábia Saudita",
                            sigla: "KSA",
                            alt: "bandeira da arabia saudita",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Escócia",
                            sigla: "SCO",
                            alt: "bandeira da escocia",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Algéria",
                            sigla: "ALG",
                            alt: "bandeira da algeria",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Chile",
                            sigla: "CHI",
                            alt: "bandeira do chile",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "L",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Marrocos",
                            sigla: "MAR",
                            alt: "bandeira do marrocos",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 2, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Ucrânia",
                            sigla: "UKR",
                            alt: "bandeira da ucrania",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Venezuela",
                            sigla: "VEN",
                            alt: "bandeira da venezuela",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Iraque",
                            sigla: "IRQ",
                            alt: "bandeira do iraque",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -2, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "M",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Uruguai",
                            sigla: "URU",
                            alt: "bandeira do uruguai",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 3, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Turquia",
                            sigla: "TUR",
                            alt: "bandeira da turquia",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Cabo Verde",
                            sigla: "CPV",
                            alt: "bandeira do cabo verde",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Israel",
                            sigla: "ISR",
                            alt: "bandeira de israel",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -3, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "N",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "EUA",
                            sigla: "USA",
                            alt: "bandeira dos estados unidos",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 2, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Noruega",
                            sigla: "NOR",
                            alt: "bandeira da noruega",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 1, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "África do Sul",
                            sigla: "RSA",
                            alt: "bandeira da africa do sul",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -1, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Bolívia",
                            sigla: "BOL",
                            alt: "bandeira da bolivia",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -2, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "O",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "México",
                            sigla: "MEX",
                            alt: "bandeira do mexico",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Polônia",
                            sigla: "POL",
                            alt: "bandeira da polonia",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Mali",
                            sigla: "MLI",
                            alt: "bandeira do mali",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Hungria",
                            sigla: "HUN",
                            alt: "bandeira da hungria",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                    ],
                },
                {
                    letra: "P",
                    times: [
                        {
                            posicao: 1,
                            status: "classificado",
                            nome: "Alemanha",
                            sigla: "GER",
                            alt: "bandeira da alemanha",
                            jogos: 1, conquistas: 1, empates: 0, derrotas: 0, dg: 3, pontos: 3,
                            ultimos: ["vitoria", "tbd", "tbd"],
                        },
                        {
                            posicao: 2,
                            status: "classificado",
                            nome: "Coreia do Sul",
                            sigla: "KOR",
                            alt: "bandeira da coreia do sul",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 3,
                            status: "eliminado",
                            nome: "Sérvia",
                            sigla: "SRB",
                            alt: "bandeira da servia",
                            jogos: 1, conquistas: 0, empates: 1, derrotas: 0, dg: 0, pontos: 1,
                            ultimos: ["empate", "tbd", "tbd"],
                        },
                        {
                            posicao: 4,
                            status: "eliminado",
                            nome: "Costa Rica",
                            sigla: "CRC",
                            alt: "bandeira da costa rica",
                            jogos: 1, conquistas: 0, empates: 0, derrotas: 1, dg: -3, pontos: 0,
                            ultimos: ["derrota", "tbd", "tbd"],
                        },
                    ],
                },
            ],
        };
    },
}).mount("#app");